[project]
name = "symbiont-cli"
version = "0.1.0"
description = ""
authors = [{ name = "lonehegelian", email = "thelonehegelian@protonmail.com" }]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "langchain-chroma>=0.1.4",
    "langchain>=0.3.0",
    "langchain-core>=0.3.5",
    "langchain-community>=0.3.0",
    "langchain-openai>=0.2.0",
    "pypdf>=5.0.0",
    "pymupdf>=1.24.10",
    "sentence-transformers>=3.1.1",
    "langchain-qdrant>=0.1.4",
    "pdfplumber>=0.11.4",
    "langchain-llm>=0.4.15",
    "unstructured[pdf]>=0.15.13",
    "libmagic>=1.0",
    "python-magic>=0.4.27",
    "colorama>=0.4.6",
    "langchainhub>=0.1.21",
    "langchain-voyageai>=0.1.2",
    "langchain-cohere>=0.3.0",
    "tqdm>=4.66.5",
    "transformers>=4.45.1",
    "torch>=2.4.1",
    "einops>=0.8.0",
    "typer>=0.16.0",
    "toml>=0.10.2",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-mock>=3.10.0",
    "pytest-docker>=1.0.0",
    "pytest-cov>=4.0.0",
]

[project.scripts]
symbiont-cli = "symbiont_cli.cli:app"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["symbiont_cli"]
